name: Linter check

on: [push]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Packages
        run: |
          npm install
      - name: Lint
        run: |
          npm run lint
